### ISSUE TITLE
Download Binary Returns 404

### ISSUE THREAD

**Issue by JeffCarpenter** [extemporelang/vscode-extempore#22]
When I use the CTRL+Shift+P -> Extempore Download Binary function, it returns a 404 error

**Comment by benswift** [comment]
Ah, thanks - that's probably because of a recent change in the naming of the zipfiles.

Can you tell me what platform you're on? I'll try and get a fix up asap.

**Comment by JeffCarpenter** [comment]
I'm on Windows 10 64-bit

**Comment by benswift** [comment]
Hey @JeffCarpenter I just pushed a fix - can you update the extension and give it another try?

**Comment by JeffCarpenter** [comment]
Thanks @benswift  - it works!
