### ISSUE TITLE
Extempore Startup

### ISSUE THREAD

**Issue by cianoc** [extemporelang/vscode-extempore#4]
VSCode should have the equivalent of C-c C-z in Emacs. That is it should be possible to start Extempore without having to mess around in the console. By default extempore should be started in the same folder as the currently active file.

**Comment by benswift** [comment]
Yeah, I agree - this is mentioned under TODO in the readme. I'm looking into it, I'm just quite new to VSCode so I'm not sure what it involves.

**Comment by benswift** [comment]
p.s. these are all good ideas, so keep 'em coming :) Hopefully there are others in the community who have the know how to help with this stuff as well.

**Comment by benswift** [comment]
added `Extempore Start` command in 171df2db62feb3ef4be30f941ab75ec93e7669f9
