### ISSUE TITLE
Load Paredit and Parinfer in Extempore Mode

### ISSUE THREAD

**Issue by cianoc** [extemporelang/vscode-extempore#6]
Probably the easiest way to do this is just to submit pull requests to:
+ https://github.com/shaunlebron/vscode-parinfer
and
+ https://github.com/clptn/code-paredit

and get Extempore added as a language mode for them. However maybe there's a more elegant way to achieve this?

**Comment by benswift** [comment]
Also, I'm not keen to load either of those as *default* - structural editing is amazing, but it can be confusing/frustrating for newbies. However, the Extempore extension should definitely play nice with parinfer/paredit.

**Comment by benswift** [comment]
I've made the pull requests, and I've put some (untested) code to check if they're active and not run the default formatting provider in 69c3a152275b7394e98e7084be91516cd60d7643

So I think that's all we'll do for the moment.
